<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE facturas [
<!ELEMENT factura (cab,detalle,pagada?)>
<!ELEMENT cab (cliente,fecha,(telefono|email))>
<!ATTLIST cab numeroF ID #REQUIRED>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT cliente (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT articulo EMPTY>
<!ATTLIST articulo codigo CDATA #REQUIRED nombre CDATA #REQUIRED cantidad CDATA #REQUIRED precio  CDATA #REQUIRED>
<!ELEMENT linea (articulo)>
<!ATTLIST linea id CDATA #REQUIRED>
<!ELEMENT facturas (factura+)>
<!ELEMENT detalle (linea+)>
<!ELEMENT pagada EMPTY>
]
>
<facturas>
	<factura>
		<cab numeroF="F1">
			<cliente>1111111A</cliente>
			<fecha>2024/02/28</fecha>
			<telefono>566541812</telefono>
		</cab>
		<detalle>
			<linea id="1">
				<articulo codigo="A01" nombre="Ruedas Michelin" cantidad="2" precio="80"/>
			</linea>
			<linea id="2">
				<articulo codigo="A01" nombre="Ruedas Michelin" cantidad="2" precio="80"/>
			</linea>
		</detalle>
		<pagada/>
		<!--ELEMNTO OPCIONAL, SÓLO SI ESTÁ PAGADA-->
	</factura>
	<factura>
	<cab numeroF="F2">
		<cliente>22222222B</cliente>
		<fecha>2022/03/28</fecha>
		<!--elemento telefono o mail-->
		<telefono>9876239486</telefono>
	</cab>
	<detalle>
		<linea id="1,2,3,4">
			<articulo codigo="A100" nombre="Filtro Aire" cantidad="2" precio="80"/>
		</linea>
		<linea id="2">
			<articulo codigo="A01" nombre="Ruedas Michelin" cantidad="1" precio="15.34"/>
		</linea>
	</detalle>
	</factura>
</facturas>
